version: 2.1

orbs:
  node: circleci/node@1.1.6

executors:
  my-executor:
    docker:
      - image: buildpack-deps:jessie
    working_directory: /tmp/test

jobs:
  flow:
    executor:
      name: node/default
    steps:
      - run: mkdir workspace
      - run: echo "Hello, world!" > echo-output
      - persist_to_workspace:
          root: /tmp/test/workspace
          paths:
            - .

  downstream:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: /tmp/test/workspace
      - run: |
          if [[ `cat /tmp/test/workspace/echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
