version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  flow:
    executor:
      name: node/default
    working_directory: ~/test
    steps:
      - run: |
          echo "Hello, world!" > echo-output
          echo $PWD
          ls -la
      - persist_to_workspace:
          root: .
          paths:
            - .

  downstream:
    executor:
      name: node/default
    working_directory: ~/test
    steps:
      - attach_workspace:
          at: ~/test
      - run: |
          echo $PWD
          ls -la
          if [[ `cat echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
